name: ml_p2
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow      = 1.23.1
  - ipython     = 8.0.1
  # - notebook    = 6.4.8
  # - jupyterlab  = 3.2.9   
  - cookiecutter= 1.7.3
  - hydra-core  = 1.1.1
  - matplotlib  = 3.5.1
  - pandas      = 1.4.0
  - git         = 2.35.0
  - pip         = 22.0.3 
    - wandb       = 0.12.10
  # - ipython=7.21.0     ## 8.0.1
  # - notebook=6.2.0     ## 6.4.8
  # - jupyterlab=3.0.10  ## jupyterlab 3.2.9   
  # - cookiecutter=1.7.2 ## 1.7.3
  # - hydra-core=1.0.6   ## 1.1.1
  # - matplotlib=3.3.4   ## 3.5.1
  # - pandas=1.2.3       ## 1.4.0
  # - git=2.30.2         ## 2.35.0
  # - pip=20.3.3         ## 22.0.3 
  # - pip:
  #     - wandb==0.10.31
